// test/visual-qa.mjs
import http from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join } from "node:path";
import puppeteer from "puppeteer-core";

const root=join(process.cwd(),"public");
const projects=[{id:1,name:"BrainDump",description:null,color:"#e7653b",icon:null,status:"active",dumpCount:3,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},{id:2,name:"Harmonix",description:null,color:"#5d83c8",icon:null,status:"active",dumpCount:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}];
const tag=(id,name)=>({id,name,color:"#72819a",dumpCount:1,createdAt:new Date().toISOString()});
const now=new Date();const iso=(offset,hour=10)=>{const value=new Date(now);value.setDate(value.getDate()+offset);value.setHours(hour,0,0,0);return value.toISOString()};
let dumps=[
  {id:1,userId:"qa",title:"Préparer le point hebdo avec l’équipe",content:"Lister les décisions et préparer les trois sujets prioritaires.",type:"task",status:"todo",priority:"high",dueAt:iso(0,10),projectId:2,project:projects[1],tags:[tag(1,"réunion")],attachments:[],favorite:true,parentId:null,createdAt:iso(-2),updatedAt:iso(0,8),archivedAt:null,completedAt:null},
  {id:2,userId:"qa",title:"Draft du plan de contenu Q3",content:"Axes éditoriaux et premières idées de formats.",type:"note",status:"inbox",priority:"normal",dueAt:iso(1,14),projectId:1,project:projects[0],tags:[tag(2,"contenu")],attachments:[],favorite:false,parentId:null,createdAt:iso(-1),updatedAt:iso(-1),archivedAt:null,completedAt:null},
  {id:3,userId:"qa",title:"Idée de mode focus sans distraction",content:"Masquer le chrome pendant une session courte.",type:"idea",status:"inbox",priority:"normal",dueAt:null,projectId:1,project:projects[0],tags:[tag(3,"ux")],attachments:[],favorite:false,parentId:null,createdAt:iso(-1),updatedAt:iso(-1),archivedAt:null,completedAt:null},
  {id:4,userId:"qa",title:"Corriger l’erreur d’export CSV",content:"Les caractères accentués cassent l’export.",type:"bug",status:"in_progress",priority:"urgent",dueAt:iso(-1,17),projectId:1,project:projects[0],tags:[tag(4,"export")],attachments:[],favorite:false,parentId:null,createdAt:iso(-4),updatedAt:iso(-1),archivedAt:null,completedAt:null},
  {id:5,userId:"qa",title:"Appeler le dentiste",content:"Prendre le rendez-vous annuel.",type:"reminder",status:"todo",priority:"normal",dueAt:iso(0,18),projectId:null,project:null,tags:[],attachments:[],favorite:false,parentId:null,createdAt:iso(-3),updatedAt:iso(-2),archivedAt:null,completedAt:null}
];
const types={".html":"text/html",".css":"text/css",".js":"text/javascript",".woff2":"font/woff2"};
function json(response,status,payload){response.writeHead(status,{"content-type":"application/json"});response.end(JSON.stringify(payload))}
async function body(request){let value="";for await(const chunk of request)value+=chunk;return value?JSON.parse(value):{}}
const server=http.createServer(async(request,response)=>{
  const url=new URL(request.url,"http://127.0.0.1");
  if(url.pathname.startsWith("/api/")){
    if(url.pathname==="/api/session")return json(response,200,{authenticated:true,user:{id:"qa",username:"matheo",displayName:"Mathéo"}});
    if(url.pathname==="/api/analyze"&&request.method==="POST"){const data=await body(request);const content=String(data.content??"").toLowerCase();return json(response,200,{type:content.includes("erreur")?"bug":content.includes("idée")?"idea":"task",priority:content.includes("urgente")?"urgent":"normal",project:content.includes("braindump")?"BrainDump":null,dueDate:content.includes("demain")?iso(1,10):null,tags:content.includes("api")?["api"]:[],confidence:91,scores:{bug:8,task:2,idea:0,reminder:0,information:0},signals:["qa"]})}
    if(url.pathname==="/api/projects")return json(response,200,projects);
    if(url.pathname==="/api/tags")return json(response,200,[tag(1,"réunion"),tag(2,"contenu"),tag(3,"ux"),tag(4,"export")]);
    if(url.pathname==="/api/today")return json(response,200,{overdue:dumps.filter((item)=>item.dueAt&&item.dueAt<iso(0,0)&&!["done","cancelled"].includes(item.status)),today:dumps.filter((item)=>item.dueAt?.slice(0,10)===iso(0).slice(0,10)),important:dumps.filter((item)=>["high","urgent"].includes(item.priority)||item.favorite),recent:dumps.slice(0,4)});
    if(url.pathname==="/api/dumps"&&request.method==="POST"){const data=await body(request);const item={...dumps[0],...data,id:Date.now(),title:data.title??null,content:data.content,project:null,tags:[],favorite:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),dueAt:data.dueAt??null,status:data.status??"inbox",priority:data.priority??"normal",attachments:[]};dumps.unshift(item);return json(response,201,item)}
    const match=url.pathname.match(/^\/api\/dumps\/(\d+)$/);if(match){const id=Number(match[1]);const item=dumps.find((dump)=>dump.id===id);if(request.method==="GET")return json(response,item?200:404,item??{error:"Introuvable"});if(request.method==="PATCH"){Object.assign(item,await body(request),{updatedAt:new Date().toISOString()});return json(response,200,item)}if(request.method==="DELETE"){dumps=dumps.filter((dump)=>dump.id!==id);response.writeHead(204);return response.end()}}
    if(url.pathname==="/api/dumps"){let result=dumps.filter((item)=>!item.archivedAt);if(url.searchParams.get("type"))result=result.filter((item)=>item.type===url.searchParams.get("type"));if(url.searchParams.get("status"))result=result.filter((item)=>item.status===url.searchParams.get("status"));if(url.searchParams.get("search")){const q=url.searchParams.get("search").toLowerCase();result=result.filter((item)=>`${item.title} ${item.content} ${item.project?.name??""} ${item.tags.map((value)=>value.name)}`.toLowerCase().includes(q))}return json(response,200,result)}
    return json(response,200,{});
  }
  const path=url.pathname==="/"?"index.html":url.pathname==="/login"?"login.html":url.pathname.slice(1);try{const data=await readFile(join(root,path));response.writeHead(200,{"content-type":types[extname(path)]??"application/octet-stream"});response.end(data)}catch{response.writeHead(404);response.end("Not found")}
});
await new Promise((resolve)=>server.listen(4319,"127.0.0.1",resolve));
const browser=await puppeteer.launch({headless:true,executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",args:["--no-sandbox"]});
const requested=process.env.VIEWPORTS?.split(",")??["1920x1080","1440x1000","1366x900","768x1024","430x932","390x844","375x812"];
const results=[];
for(const item of requested){const[width,height]=item.split("x").map(Number);const page=await browser.newPage();await page.setViewport({width,height,deviceScaleFactor:1});const errors=[];page.on("console",(message)=>{if(message.type()==="error")errors.push(message.text())});page.on("pageerror",(error)=>errors.push(error.message));await page.goto("http://127.0.0.1:4319/",{waitUntil:"networkidle0"});const name=width===1536?"hero-repro":width===1440?"desktop":width===390?"mobile":`user-${width}`;await page.screenshot({path:`.impeccable/review/${name}.png`,fullPage:true});const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,title:document.querySelector("h1")?.textContent}));results.push({viewport:item,...metrics,errors});await page.close()}
const flow=await browser.newPage();await flow.setViewport({width:1366,height:900});await flow.goto("http://127.0.0.1:4319/",{waitUntil:"networkidle0"});await flow.type("#capture-content","Corriger l’erreur API urgente sur BrainDump demain");await flow.waitForSelector("#triage-preview:not([hidden])");const desktopTriage=await flow.$eval("#triage-preview",(node)=>node.textContent);await flow.screenshot({path:".impeccable/review/triage-desktop.png"});await flow.click("[data-open='1']");await flow.waitForSelector("#detail-form:not([hidden])");await flow.click("[data-view='projects']");await flow.waitForSelector("#project-form");await flow.keyboard.down("Meta");await flow.keyboard.press("KeyK");await flow.keyboard.up("Meta");await flow.waitForSelector("#search-dialog[open]");await flow.type("#global-search","export");await new Promise((resolve)=>setTimeout(resolve,300));const searchCount=await flow.$$eval("[data-search-open]",(items)=>items.length);await flow.close();
const mobile=await browser.newPage();await mobile.setViewport({width:390,height:844});await mobile.goto("http://127.0.0.1:4319/",{waitUntil:"networkidle0"});await mobile.click("#mobile-add");await mobile.waitForSelector("#mobile-capture[open]");await mobile.type("#mobile-content","Une idée mobile pour BrainDump");await mobile.waitForSelector("#mobile-triage-preview:not([hidden])");const mobileTriage=await mobile.$eval("#mobile-triage-preview",(node)=>node.textContent);const mobileSheet=await mobile.evaluate(()=>{const sheet=document.querySelector("#mobile-capture")?.getBoundingClientRect();const action=document.querySelector("#mobile-save")?.getBoundingClientRect();return {fits:Boolean(sheet&&action&&sheet.top>=0&&sheet.bottom<=innerHeight&&action.bottom<=innerHeight),sheet:sheet&&{top:sheet.top,bottom:sheet.bottom,height:sheet.height},action:action&&{top:action.top,bottom:action.bottom},viewport:innerHeight}});await mobile.screenshot({path:".impeccable/review/triage-mobile.png"});await mobile.click("#mobile-save");await mobile.waitForSelector("#mobile-capture:not([open])");const mobileSaved=await mobile.evaluate(()=>document.querySelector("#mobile-capture")?.open===false);await mobile.close();results.push({flows:{detail:true,projects:true,searchResults:searchCount,desktopTriage,mobileTriage,mobileCapture:mobileSheet,mobileCaptureSaved:mobileSaved}});
for(const [width,height,name] of [[1440,1000,"login-desktop"],[390,844,"login-mobile"]]){const login=await browser.newPage();await login.setJavaScriptEnabled(false);await login.setViewport({width,height});await login.goto("http://127.0.0.1:4319/login",{waitUntil:"networkidle0"});await login.screenshot({path:`.impeccable/review/${name}.png`,fullPage:true});const overflow=await login.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);results.push({login:name,overflow});await login.close()}
await browser.close();server.close();console.log(JSON.stringify(results,null,2));
